BRAINSTEMS_TOKEN_NAME = "Brainstems Token";
BRAINSTEMS_TOKEN_SYMBOL = "STEMS";
BRAINSTEMS_TOKEN_EVENTS = {
  TRANSFER: "Transfer",
};
BRAINSTEMS_TOKEN_DECIMALS = 18;

module.exports = {
  BRAINSTEMS_TOKEN_NAME,
  BRAINSTEMS_TOKEN_SYMBOL,
  BRAINSTEMS_TOKEN_DECIMALS
};
